### ISSUE TITLE
Question: using your models for testing without re-training?

### ISSUE THREAD

**Issue by achiatti** [microsoft/ORBIT-Dataset#2]
Thank you for sharing this great project and data.
What is the recommended procedure for running your baseline models (pre-trained on ORBIT) for inference, without having to re-train? Can inference be run on CPU-only environments?

**Comment by danielamassiceti** [comment]
Hi there

Apologies for the delayed response. I plan to add the pre-trained checkpoints to the repo in the next 1-2 weeks. Will notify you here when they're up. They can be run on CPU-only (see the --gpu flag) but it will take a fair while longer. To make it faster you can reduce the number of clips sampled for context video at test time (--test_context_num_clips) and the number of tasks sampled per test user (--test_tasks_per_user).

**Comment by danielamassiceti** [comment]
Hi there - I have added the trained checkpoints with instructions to run as test-only! :)
